import type { Category } from '@/types';

export const DEFAULT_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Food', icon: 'restaurant', color: '#F97316', type: 'expense', isDefault: true },
  { name: 'Transport', icon: 'car', color: '#3B82F6', type: 'expense', isDefault: true },
  { name: 'Shopping', icon: 'bag-handle', color: '#A855F7', type: 'expense', isDefault: true },
  { name: 'Bills', icon: 'receipt', color: '#6366F1', type: 'expense', isDefault: true },
  { name: 'Entertainment', icon: 'film', color: '#EC4899', type: 'expense', isDefault: true },
  { name: 'Health', icon: 'medkit', color: '#14B8A6', type: 'expense', isDefault: true },
  { name: 'Education', icon: 'school', color: '#0EA5E9', type: 'expense', isDefault: true },
  { name: 'Rent', icon: 'home', color: '#78716C', type: 'expense', isDefault: true },
  { name: 'Other', icon: 'ellipse', color: '#64748B', type: 'expense', isDefault: true },
  { name: 'Salary', icon: 'cash', color: '#059669', type: 'income', isDefault: true },
  { name: 'Freelance', icon: 'laptop-outline', color: '#0D9488', type: 'income', isDefault: true },
  { name: 'Investment', icon: 'trending-up', color: '#2563EB', type: 'income', isDefault: true },
  { name: 'Gift', icon: 'gift', color: '#DB2777', type: 'income', isDefault: true },
];

export const CATEGORY_ICONS = [
  'restaurant',
  'cafe',
  'car',
  'bus',
  'bag-handle',
  'cart',
  'receipt',
  'flash',
  'film',
  'game-controller',
  'medkit',
  'fitness',
  'school',
  'home',
  'gift',
  'cash',
  'card',
  'laptop-outline',
  'trending-up',
  'airplane',
  'paw',
  'cut',
  'phone-portrait',
  'ellipse',
] as const;

export const CATEGORY_COLORS = [
  '#F97316',
  '#3B82F6',
  '#A855F7',
  '#6366F1',
  '#EC4899',
  '#14B8A6',
  '#0EA5E9',
  '#78716C',
  '#059669',
  '#E11D48',
  '#D97706',
  '#0F766E',
];
